### ISSUE TITLE
每个模型的学习率设定有什么经验吗？

### ISSUE THREAD

**Issue by shipengai** [TideDra/VL-RLHF#15]
看了里面的script，每个模型的学习率和lora rank都不太一样，请问这个有什么调整经验吗？
另外，再想请教下，vit和llm中的mlp不训练，只训练llm的lora效果会怎么样

**Comment by TideDra** [comment]
> 看了里面的script，每个模型的学习率和lora rank都不太一样，请问这个有什么调整经验吗？
> 
> 另外，再想请教下，vit和llm中的mlp不训练，只训练llm的lora效果会怎么样

训练参数参考各模型官方微调脚本的参数。 一般只训llm，之前试过带上vision模块会变差

**Comment by shipengai** [comment]
@TideDra ，非常感谢回复，这里说的vision模块对应llava的话，是不是指adapter部分，中间的2层fc

**Comment by TideDra** [comment]
> @TideDra ，非常感谢回复，这里说的vision模块对应llava的话，是不是指adapter部分，中间的2层fc

指vit。 每个模型的微调模块都是参照官方脚本
